# MCO Repo docs
- name: "Observability Operator README"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/README.md"
- name: "Observability Operator Debug"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/docs/debug.md"
- name: "Observability Operator Alert Forwarding Sequence Diagram"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/docs/diagrams/components/metrics-collection-alert-forwarding.md"
- name: "Observability Operator Bootstraping Hub Sequence Diagram"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/docs/diagrams/architecture/observability-bootstrapping-hub.md"
- name: "Observability Operator Bootstraping Managed Cluster Sequence Diagram"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/docs/diagrams/architecture/observability-bootstrapping-managed.md"
- name: "Observability Operator Status Propagation Sequence Diagram"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/docs/diagrams/workflows/metrics-collection-status-propagation.md"
- name: "Observability Operator Placement Delete Sequence Diagram"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/docs/diagrams/workflows/observability-placement-delete-flow.md"
- name: "Observability Operator Addon Status Design"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/operators/endpointmetrics/doc/design/addon-status.md"
- name: "Observability Operator RBAC Query Proxy README"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/proxy/README.md"
- name: "Observability Dev Preview"
  url: "https://github.com/stolostron/stolostron/blob/main/dev-preview/README.md"
- name: "MultiClusterObservability CRD"
  url: "https://github.com/stolostron/multicluster-observability-operator/blob/release-2.15/operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml"
  type: "crd"

# Thanos docs
- name: "Thanos Component Query Frontend"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/components/query-frontend.md"
- name: "Thanos Component Receive"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/components/receive.md"
- name: "Thanos Component Rule"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/components/rule.md"
- name: "Thanos Component Store"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/components/store.md"
- name: "Thanos Component Query"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/components/query.md"
- name: "Thanos Component Tools"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/components/tools.md"
- name: "Thanos Blog Life Of a Sample part I"
  url: "https://github.com/thanos-io/thanos/blob/main/docs/blog/2023-11-20-life-of-a-sample-part-1.md"
- name: "Thanos Blog Life Of a Sample part II"
  url: "https://github.com/thanos-io/thanos/blob/main/docs/blog/2023-11-20-life-of-a-sample-part-2.md"
- name: "Thanos Operating Index Header"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/operating/binary-index-header.md"
- name: "Thanos Operating Troubleshoot Compactor"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/operating/compactor-backlog.md"
- name: "Thanos Operating Troubleshooting"
  url: "https://github.com/thanos-io/thanos/blob/v0.39.2/docs/operating/troubleshooting.md"

# OCM CRDs
- name: "OCM ClusterManagementAddOn CRD"
  url: "https://github.com/open-cluster-management-io/api/blob/main/addon/v1beta1/0000_00_addon.open-cluster-management.io_clustermanagementaddons.crd.yaml"
  type: "crd"
- name: "OCM ManagedClusterAddOn CRD"
  url: "https://github.com/open-cluster-management-io/api/blob/main/addon/v1beta1/0000_01_addon.open-cluster-management.io_managedclusteraddons.crd.yaml"
  type: "crd"
- name: "OCM AddOnDeploymentConfig CRD"
  url: "https://github.com/open-cluster-management-io/api/blob/main/addon/v1beta1/0000_02_addon.open-cluster-management.io_addondeploymentconfigs.crd.yaml"
  type: "crd"
- name: "OCM ManifestWork CRD"
  url: "https://github.com/open-cluster-management-io/api/blob/main/addon/v1beta1/0000_02_addon.open-cluster-management.io_addondeploymentconfigs.crd.yaml"
  type: "crd"

# OCM Docs
- name: "OCM What is ManifestWork"
  url: "https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/main/content/en/docs/concepts/work-distribution/manifestwork.md"
- name: "OCM What is Placement"
  url: "https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/6a5e60327da30c7fc249e93468811062e43a9c48/content/en/docs/concepts/content-placement/placement.md"
- name: "OCM Add-on enablement"
  url: "https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/6a5e60327da30c7fc249e93468811062e43a9c48/content/en/docs/getting-started/installation/addon-management.md"

# Prometheus Operator CRDs
- name: "Prometheus PrometheusAgent CRD"
  url: "https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml"
  type: "crd"
- name: "Prometheus PrometheusRules CRD"
  url: "https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml"
  type: "crd"
- name: "Prometheus ScrapeConfigs CRD"
  url: "https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml"
  type: "crd"

